"""Generate the deterministic, entirely synthetic documents used by this example."""

from __future__ import annotations

import argparse
import io
import sys
import zipfile
from datetime import UTC, datetime
from pathlib import Path

from docx import Document

ROOT = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
FIXED_ZIP_TIME = (2026, 1, 1, 0, 0, 0)

APPROVAL_MARKDOWN = """# Synthetic approval memorandum

On January 12, 2026, Robert Williams approved Contract #428.

This fictional record exists only to demonstrate DocChrono.
"""

PAYMENT_EMAIL = """From: treasury@acme.test
To: records@acme.test
Date: Tue, 20 Jan 2026 08:30:00 -0600
Subject: Synthetic payment record
Message-ID: <payment-932@acme.test>
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

On January 20, 2026, Acme Corporation paid Payment #932 for Contract #428.

This message and every identity in it are fictional test data.
"""


def _canonical_docx() -> bytes:
    """Return a DOCX with stable XML and ZIP metadata."""

    document = Document()
    properties = document.core_properties
    fixed_datetime = datetime(2026, 1, 1, tzinfo=UTC)
    properties.author = "DocChrono synthetic data generator"
    properties.created = fixed_datetime
    properties.last_modified_by = "DocChrono synthetic data generator"
    properties.modified = fixed_datetime
    properties.revision = 1
    properties.subject = "Synthetic contract evidence"
    properties.title = "Synthetic Contract Record"

    document.add_heading("Synthetic Contract Record", level=0)
    document.add_paragraph("On January 5, 2026, Acme Corporation signed Contract #428.")
    document.add_paragraph("This fictional record exists only to demonstrate DocChrono.")

    raw_package = io.BytesIO()
    document.save(raw_package)

    canonical_package = io.BytesIO()
    with (
        zipfile.ZipFile(io.BytesIO(raw_package.getvalue()), "r") as source,
        zipfile.ZipFile(
            canonical_package,
            "w",
            compression=zipfile.ZIP_STORED,
        ) as target,
    ):
        for name in sorted(source.namelist()):
            info = zipfile.ZipInfo(name, date_time=FIXED_ZIP_TIME)
            info.compress_type = zipfile.ZIP_STORED
            info.create_system = 3
            info.external_attr = 0o600 << 16
            target.writestr(info, source.read(name))
    return canonical_package.getvalue()


def expected_files() -> dict[str, bytes]:
    """Build all expected input files in memory."""

    return {
        "approval.md": APPROVAL_MARKDOWN.encode("utf-8"),
        "contract_record.docx": _canonical_docx(),
        "payment.eml": PAYMENT_EMAIL.replace("\n", "\r\n").encode("utf-8"),
    }


def generate(*, check: bool) -> int:
    expected = expected_files()
    if check:
        actual_names: set[str] = (
            {path.name for path in DATA_DIR.iterdir() if path.is_file()}
            if DATA_DIR.is_dir()
            else set()
        )
        expected_names = set(expected)
        failures: list[str] = []
        if actual_names != expected_names:
            failures.append(
                f"file set differs (expected {sorted(expected_names)}, got {sorted(actual_names)})"
            )
        for name, content in expected.items():
            path = DATA_DIR / name
            if not path.is_file() or path.read_bytes() != content:
                failures.append(f"{name} is missing or differs from generated bytes")
        if failures:
            for failure in failures:
                print(f"ERROR: {failure}", file=sys.stderr)
            return 1
        print("Synthetic data is up to date.")
        return 0

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in expected.items():
        (DATA_DIR / name).write_bytes(content)
    print(f"Generated {len(expected)} synthetic documents in {DATA_DIR.relative_to(ROOT)}.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if committed data does not exactly match a fresh generation",
    )
    args = parser.parse_args()
    return generate(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
